"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { api, ApiError, type CostComponents, type CostRow, type PricingResult } from "@/lib/api";

const naira = (kobo?: number) => kobo === undefined ? "—" : new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN" }).format(kobo / 100);
const toKobo = (raw: string) => { const value = raw.trim(); if (!/^\d+(\.\d{0,2})?$/.test(value)) return null; const [whole, fraction = ""] = value.split("."); const result = Number(whole) * 100 + Number(fraction.padEnd(2, "0")); return Number.isSafeInteger(result) ? result : null; };
const blank: CostComponents = { supplier_cost_kobo: 0, shipping_cost_kobo: 0, packaging_cost_kobo: 0, payment_fee_kobo: 0, tax_import_cost_kobo: 0, other_allocated_cost_kobo: 0 };

export default function CostManager({ slug }: { slug: string }) {
  const [rows, setRows] = useState<CostRow[]>([]); const [selected, setSelected] = useState<CostRow | null>(null); const [cost, setCost] = useState<CostComponents>(blank); const [result, setResult] = useState<PricingResult | null>(null); const [explicitFloor, setExplicitFloor] = useState(""); const [lockReason, setLockReason] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const load = useCallback(async () => { try { const response = await api.costs(slug, "?limit=100"); setRows(response.costs); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Could not load costs."); } finally { setLoading(false); } }, [slug]);
  useEffect(() => { void load(); }, [load]);
  async function edit(row: CostRow) { setSelected(row); setResult(null); setExplicitFloor(""); setLockReason(""); setMessage(""); setError(""); if (!row.cost_id) { setCost(blank); return; } try { const detail = await api.productCost(slug, row.product_id); setCost(detail.cost); setResult(await api.evaluatePrice(slug, row.product_id)); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Could not load cost."); } }
  function setField(field: keyof CostComponents, raw: string) { const value = toKobo(raw); if (value !== null) setCost(previous => ({ ...previous, [field]: value })); }
  async function save(event: FormEvent) { event.preventDefault(); if (!selected) return; setSaving(true); setError(""); setMessage(""); try { await api.setCost(slug, selected.product_id, cost); setResult(await api.evaluatePrice(slug, selected.product_id)); setMessage("Cost saved and price floor recalculated."); await load(); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Could not save cost."); } finally { setSaving(false); } }
  async function saveFloor() { if (!selected) return; const floor = toKobo(explicitFloor); if (floor === null) { setError("Enter a valid explicit floor in naira."); return; } setSaving(true); try { await api.setPricePolicy(slug, { scope_type: "product", product_id: selected.product_id, minimum_price_kobo: floor, rounding_increment_kobo: 100 }); setResult(await api.evaluatePrice(slug, selected.product_id)); setMessage("Explicit product floor saved."); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Could not save price floor."); } finally { setSaving(false); } }
  async function toggleLock() { if (!selected || !result) return; const locking = !result.product_locked; if (locking && !lockReason.trim()) { setError("Enter a reason before locking this product."); return; } setSaving(true); try { await api.setPriceLock(slug, selected.product_id, locking, lockReason); setResult(await api.evaluatePrice(slug, selected.product_id)); setMessage(locking ? "Product locked from pricing activity." : "Product lock removed."); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Could not update product lock."); } finally { setSaving(false); } }
  async function upload(file: File) { setSaving(true); setError(""); setMessage(""); try { const imported = await api.importCosts(slug, file); setMessage(`Imported ${imported.imported}; ${imported.failed} failed.`); await load(); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Import failed."); } finally { setSaving(false); } }
  return <div className="stack">
    <section className="panel"><div className="row between"><div><h2>Cost and margin overview</h2><p className="muted">Exact integer kobo calculations. Missing costs never receive a price floor.</p></div><label className="btn">Import CSV<input type="file" accept=".csv,text/csv" hidden disabled={saving} onChange={event => { const file=event.target.files?.[0]; if(file) void upload(file); }} /></label></div></section>
    {error && <div className="alert alert-error">{error}</div>}{message && <div className="alert alert-success">{message}</div>}
    <div className="grid cost-grid">
      <section className="panel table-wrap"><table><thead><tr><th>Product</th><th>Current</th><th>Landed cost</th><th>Margin</th><th>Safe floor</th><th>Status</th><th></th></tr></thead><tbody>{loading ? <tr><td colSpan={7}>Loading…</td></tr> : rows.map(row => <tr key={row.product_id}><td><strong>{row.product_name}</strong><div className="muted">{row.sku || "Missing SKU"}</div></td><td>{naira(row.current_price_kobo)}</td><td>{naira(row.landed_cost_kobo)}</td><td>{row.margin_bps === undefined ? "—" : `${(row.margin_bps / 100).toFixed(2)}%`}</td><td>{naira(row.minimum_price_kobo)}</td><td><span className="badge">{row.status.replaceAll("_", " ")}</span></td><td><button className="btn" onClick={() => void edit(row)}>Edit</button></td></tr>)}</tbody></table></section>
      {selected && <form className="panel stack" onSubmit={save}><h2>{selected.product_name}</h2>{([['Supplier', 'supplier_cost_kobo'], ['Shipping', 'shipping_cost_kobo'], ['Packaging', 'packaging_cost_kobo'], ['Payment fee', 'payment_fee_kobo'], ['Tax/import', 'tax_import_cost_kobo'], ['Other', 'other_allocated_cost_kobo']] as const).map(([label, field]) => <div className="field" key={field}><label>{label} (₦)</label><input inputMode="decimal" value={(cost[field] / 100).toFixed(2)} onChange={event => setField(field, event.target.value)} /></div>)}<button className="btn btn-primary" disabled={saving}>{saving ? "Saving…" : "Save cost"}</button>{result && <div className="alert alert-warning"><strong>{result.status.replaceAll("_", " ")}</strong><div>Minimum profitable price: {naira(result.minimum_profitable_price_kobo)}</div><div>Current margin: {(result.current_margin_bps / 100).toFixed(2)}%</div><div>{result.reason}</div></div>}<div className="field"><label>Explicit product floor (₦)</label><input inputMode="decimal" value={explicitFloor} onChange={event => setExplicitFloor(event.target.value)} placeholder="Optional override" /></div><button type="button" className="btn" disabled={saving || explicitFloor === ""} onClick={() => void saveFloor()}>Save explicit floor</button><div className="field"><label>Product lock reason</label><input value={lockReason} onChange={event => setLockReason(event.target.value)} placeholder="e.g. Fragile item" /></div><button type="button" className={`btn ${result?.product_locked ? "" : "btn-danger"}`} disabled={saving || !result} onClick={() => void toggleLock()}>{result?.product_locked ? "Remove product lock" : "Lock product pricing"}</button></form>}
    </div>
  </div>;
}
