"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { api, ApiError, type CostRow, type PricingResult, type PricingRule } from "@/lib/api";

const inputOf = (rule: PricingRule) => ({ name: rule.name, scope_type: rule.scope_type, product_id: rule.product_id || "", variant_id: rule.variant_id || "", category_id: rule.category_id || "", minimum_margin_bps: rule.minimum_margin_bps, maximum_change_bps: rule.maximum_change_bps, maximum_price_kobo: rule.maximum_price_kobo, rounding_increment_kobo: rule.rounding_increment_kobo, priority: rule.priority, active: rule.active, cooldown_minutes: rule.cooldown_minutes, conditions: rule.conditions ?? {} });

export default function RulesManager({ slug }: { slug: string }) {
  const [rules, setRules] = useState<PricingRule[]>([]); const [products, setProducts] = useState<CostRow[]>([]); const [form, setForm] = useState({ name: "", scope_type: "store" as PricingRule["scope_type"], product_id: "", category_id: "", minimum_margin_bps: 2500, maximum_change_bps: 2000, rounding_increment_kobo: 100, priority: 100, cooldown_minutes: 0 }); const [preview, setPreview] = useState<PricingResult[]>([]); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [working, setWorking] = useState(false);
  const load = useCallback(async () => { try { const [r, c] = await Promise.all([api.pricingRules(slug), api.costs(slug, "?limit=100")]); setRules(r.rules); setProducts(c.costs); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Could not load pricing rules."); } }, [slug]);
  useEffect(() => { void load(); }, [load]);
  const payload = () => ({ ...form, variant_id: "", maximum_price_kobo: undefined, active: false, conditions: {} });
  async function create(event: FormEvent) { event.preventDefault(); setWorking(true); setError(""); setMessage(""); try { await api.createPricingRule(slug, payload()); setMessage("Rule created inactive. Preview it before activation."); setForm(previous => ({ ...previous, name: "" })); await load(); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Could not create rule."); } finally { setWorking(false); } }
  async function simulate(rule: PricingRule) { setWorking(true); setError(""); try { const draft = { id: rule.id, name: rule.name, scope_type: rule.scope_type, product_id: rule.product_id, variant_id: rule.variant_id, category_id: rule.category_id, minimum_margin_bps: rule.minimum_margin_bps, maximum_change_bps: rule.maximum_change_bps, rounding_increment_kobo: rule.rounding_increment_kobo, priority: rule.priority, active: true, conditions: rule.conditions ?? {} };
		const response = await api.simulateRules(slug, products.filter(product => product.landed_cost_kobo !== undefined).map(product => product.product_id), draft); setPreview(response.results as PricingResult[]); setMessage(`Simulated ${response.results.length} products. No prices were changed.`); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Simulation failed."); } finally { setWorking(false); } }
  async function toggle(rule: PricingRule) { setWorking(true); setError(""); try { await api.updatePricingRule(slug, rule.id, { ...inputOf(rule), active: !rule.active, expected_version: rule.version }); setMessage(`${rule.name} ${rule.active ? "deactivated" : "activated"}.`); await load(); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Rule update failed."); } finally { setWorking(false); } }
  async function remove(rule: PricingRule) { if (!window.confirm(`Delete rule “${rule.name}”?`)) return; setWorking(true); try { await api.deletePricingRule(slug, rule.id); await load(); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Delete failed."); } finally { setWorking(false); } }
  return <div className="stack">
    <section className="panel"><h2>Rule precedence</h2><p className="muted">Product lock → explicit product floor/ceiling → product rule → variant rule → category rule → store rule → system safety floor.</p></section>
    {error && <div className="alert alert-error">{error}</div>}{message && <div className="alert alert-success">{message}</div>}
    <div className="grid pricing-grid"><form className="panel stack" onSubmit={create}><h2>Create pricing rule</h2><div className="field"><label>Name</label><input required minLength={3} value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></div><div className="field"><label>Scope</label><select value={form.scope_type} onChange={e => setForm({ ...form, scope_type: e.target.value as PricingRule["scope_type"] })}><option value="store">Store</option><option value="product">Product</option><option value="category">Category</option></select></div>{form.scope_type === "product" && <div className="field"><label>Product</label><select required value={form.product_id} onChange={e => setForm({ ...form, product_id: e.target.value })}><option value="">Select product</option>{products.map(product => <option key={product.product_id} value={product.product_id}>{product.product_name}</option>)}</select></div>}{form.scope_type === "category" && <div className="field"><label>Category UUID</label><input required value={form.category_id} onChange={e => setForm({ ...form, category_id: e.target.value })} /></div>}<div className="field"><label>Minimum margin (%)</label><input type="number" min="0.01" max="99.99" step="0.01" value={form.minimum_margin_bps / 100} onChange={e => setForm({ ...form, minimum_margin_bps: Math.round(Number(e.target.value) * 100) })} /></div><div className="field"><label>Maximum change (%)</label><input type="number" min="0.01" max="100" value={form.maximum_change_bps / 100} onChange={e => setForm({ ...form, maximum_change_bps: Math.round(Number(e.target.value) * 100) })} /></div><div className="field"><label>Rounding increment (kobo)</label><input type="number" min="1" value={form.rounding_increment_kobo} onChange={e => setForm({ ...form, rounding_increment_kobo: Number(e.target.value) })} /></div><div className="field"><label>Priority</label><input type="number" min="1" value={form.priority} onChange={e => setForm({ ...form, priority: Number(e.target.value) })} /></div><button className="btn btn-primary" disabled={working}>Create inactive rule</button></form>
      <section className="panel table-wrap"><h2>Rules</h2><table><thead><tr><th>Name</th><th>Scope</th><th>Margin</th><th>Max move</th><th>Priority</th><th>Status</th><th></th></tr></thead><tbody>{rules.map(rule => <tr key={rule.id}><td>{rule.name}</td><td>{rule.scope_type}</td><td>{(rule.minimum_margin_bps / 100).toFixed(2)}%</td><td>{(rule.maximum_change_bps / 100).toFixed(2)}%</td><td>{rule.priority}</td><td><span className={`badge ${rule.active ? "badge-success" : ""}`}>{rule.active ? "active" : "inactive"}</span></td><td><div className="row"><button className="btn" disabled={working} onClick={() => void simulate(rule)}>Simulate</button><button className="btn" disabled={working} onClick={() => void toggle(rule)}>{rule.active ? "Disable" : "Activate"}</button><button className="btn btn-danger" disabled={working} onClick={() => void remove(rule)}>Delete</button></div></td></tr>)}</tbody></table></section></div>
    {preview.length > 0 && <section className="panel table-wrap"><h2>Simulation result</h2><p className="muted">Preview only. Phase 3 never changes WooCommerce prices.</p><table><thead><tr><th>Product</th><th>Status</th><th>Current margin</th><th>Safe floor</th><th>Reason</th></tr></thead><tbody>{preview.map(result => <tr key={result.product_id}><td>{products.find(product => product.product_id === result.product_id)?.product_name ?? result.product_id}</td><td>{result.status.replaceAll("_", " ")}</td><td>{((result.current_margin_bps ?? 0) / 100).toFixed(2)}%</td><td>{result.minimum_profitable_price_kobo === undefined ? "—" : `₦${(result.minimum_profitable_price_kobo / 100).toLocaleString("en-NG")}`}</td><td>{result.reason}</td></tr>)}</tbody></table></section>}
  </div>;
}
